// Code generated by goctl. DO NOT EDIT.
package types

type GetOrderReq struct {
	Id string `path:"id"`
}

type GetOrderReply struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type AddOrderReq struct {
	Name string `json:"name"`
}

type AddOrderReply struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
